version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./laravel:/work
      - ./.env:/work/.env
  web:
    image: nginx:1.18-alpine
    ports:
      - 8080:80
    volumes:
      - ./laravel:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  db:
    build: ./infra/mysql
    #image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - ${DB_PORT}:3306
    volumes:      
      - ./infra/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./infra/mysql/data:/var/lib/mysql
